import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import NavLinks from "@/components/NavLinks";
import Header from "@/components/Header";
import { ToastContainer } from "react-toastify";

const notoSerifBengali=Noto_Serif_Bengali({
 
  subsets: ["latin",'bengali'],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${notoSerifBengali.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        
        <div className="container mx-auto">
        <Header />
        </div>
        {children}
         <ToastContainer />
        <Footer/>
        </body>
    </html>
  );
}
